[application]
name = "rusty-films"
# desktop, web, mobile, ssr
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "🦀 | Rusty Films"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
# serve: [dev-server] only
style = []
script = []
